### ISSUE TITLE
IDE cannot resolve any symbol from react node_modules folder

### ISSUE THREAD

**Issue by ValeryLosik** [boennemann/alle#6]
Hi @boennemann 
 I tried to use your approach and faced the issue with resolving @types from root node_modules folder.
Across all my subpackages IDE can't resolve any symbol from 'react' package.However,project build is  successful and other packages also are recognizable by IDE. I understand, that it is not a problem of your solution itself but maybe you also faced this issue.

**Comment by 0x6a68** [comment]
isn't this a configuration in your `tsconfig.json` ?

**Comment by ValeryLosik** [comment]
For me it seems that configuration is fine,because,as I said,project builds successfully with this tsconfig.json. I believe that  IDE has problems with such project structure and I thought,maybe there is some
kind of additional setup for IDE(marking folders as resource or something like that).
